#############################################################################
# Makefile for building: Solution
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  Solution.pro
# Template: subdirs
# Command: C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\bin\qmake.exe -o Makefile Solution.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-Theme \
		sub-Utilities \
		sub-Database \
		sub-Model \
		sub-DAO \
		sub-BLL \
		sub-Instrument \
		sub-HumaBlotPro \
		sub-Analysis


sub-Theme-qmake_all:  FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	cd Theme\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && $(MAKE) -f Makefile qmake_all
sub-Theme: $(MAKEFILE) FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Theme-make_first-ordered: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Theme-make_first: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Theme-all-ordered: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Theme-all: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Theme-clean-ordered: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Theme-clean: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Theme-distclean-ordered: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Theme-distclean: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Theme-install_subtargets-ordered: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Theme-install_subtargets: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Theme-uninstall_subtargets-ordered: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Theme-uninstall_subtargets: FORCE
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Utilities-qmake_all: sub-Theme-qmake_all FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	cd Utilities\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && $(MAKE) -f Makefile qmake_all
sub-Utilities: $(MAKEFILE) FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Utilities-make_first-ordered: sub-Theme-make_first-ordered  FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Utilities-make_first: FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Utilities-all-ordered: sub-Theme-all-ordered  FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Utilities-all: FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Utilities-clean-ordered: sub-Theme-clean-ordered  FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Utilities-clean: FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Utilities-distclean-ordered: sub-Theme-distclean-ordered  FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Utilities-distclean: FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Utilities-install_subtargets-ordered: sub-Theme-install_subtargets-ordered  FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Utilities-install_subtargets: FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Utilities-uninstall_subtargets-ordered: sub-Theme-uninstall_subtargets-ordered  FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Utilities-uninstall_subtargets: FORCE
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Database-qmake_all: sub-Utilities-qmake_all FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	cd Database\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && $(MAKE) -f Makefile qmake_all
sub-Database: $(MAKEFILE) FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Database-make_first-ordered: sub-Utilities-make_first-ordered  FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Database-make_first: FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Database-all-ordered: sub-Utilities-all-ordered  FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Database-all: FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Database-clean-ordered: sub-Utilities-clean-ordered  FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Database-clean: FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Database-distclean-ordered: sub-Utilities-distclean-ordered  FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Database-distclean: FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Database-install_subtargets-ordered: sub-Utilities-install_subtargets-ordered  FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Database-install_subtargets: FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Database-uninstall_subtargets-ordered: sub-Utilities-uninstall_subtargets-ordered  FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Database-uninstall_subtargets: FORCE
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Model-qmake_all: sub-Database-qmake_all FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	cd Model\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && $(MAKE) -f Makefile qmake_all
sub-Model: $(MAKEFILE) FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Model-make_first-ordered: sub-Database-make_first-ordered  FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Model-make_first: FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Model-all-ordered: sub-Database-all-ordered  FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Model-all: FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Model-clean-ordered: sub-Database-clean-ordered  FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Model-clean: FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Model-distclean-ordered: sub-Database-distclean-ordered  FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Model-distclean: FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Model-install_subtargets-ordered: sub-Database-install_subtargets-ordered  FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Model-install_subtargets: FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Model-uninstall_subtargets-ordered: sub-Database-uninstall_subtargets-ordered  FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Model-uninstall_subtargets: FORCE
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DAO-qmake_all: sub-Model-qmake_all FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	cd DAO\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && $(MAKE) -f Makefile qmake_all
sub-DAO: $(MAKEFILE) FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DAO-make_first-ordered: sub-Model-make_first-ordered  FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DAO-make_first: FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DAO-all-ordered: sub-Model-all-ordered  FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DAO-all: FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DAO-clean-ordered: sub-Model-clean-ordered  FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DAO-clean: FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DAO-distclean-ordered: sub-Model-distclean-ordered  FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DAO-distclean: FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DAO-install_subtargets-ordered: sub-Model-install_subtargets-ordered  FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DAO-install_subtargets: FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DAO-uninstall_subtargets-ordered: sub-Model-uninstall_subtargets-ordered  FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DAO-uninstall_subtargets: FORCE
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-BLL-qmake_all: sub-DAO-qmake_all FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	cd BLL\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && $(MAKE) -f Makefile qmake_all
sub-BLL: $(MAKEFILE) FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-BLL-make_first-ordered: sub-DAO-make_first-ordered  FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-BLL-make_first: FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-BLL-all-ordered: sub-DAO-all-ordered  FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-BLL-all: FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-BLL-clean-ordered: sub-DAO-clean-ordered  FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-BLL-clean: FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-BLL-distclean-ordered: sub-DAO-distclean-ordered  FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-BLL-distclean: FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-BLL-install_subtargets-ordered: sub-DAO-install_subtargets-ordered  FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-BLL-install_subtargets: FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-BLL-uninstall_subtargets-ordered: sub-DAO-uninstall_subtargets-ordered  FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-BLL-uninstall_subtargets: FORCE
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Instrument-qmake_all: sub-BLL-qmake_all FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	cd Instrument\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && $(MAKE) -f Makefile qmake_all
sub-Instrument: $(MAKEFILE) FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Instrument-make_first-ordered: sub-BLL-make_first-ordered  FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Instrument-make_first: FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Instrument-all-ordered: sub-BLL-all-ordered  FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Instrument-all: FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Instrument-clean-ordered: sub-BLL-clean-ordered  FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Instrument-clean: FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Instrument-distclean-ordered: sub-BLL-distclean-ordered  FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Instrument-distclean: FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Instrument-install_subtargets-ordered: sub-BLL-install_subtargets-ordered  FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Instrument-install_subtargets: FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Instrument-uninstall_subtargets-ordered: sub-BLL-uninstall_subtargets-ordered  FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Instrument-uninstall_subtargets: FORCE
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-HumaBlotPro-qmake_all: sub-Instrument-qmake_all FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	cd HumaBlotPro\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && $(MAKE) -f Makefile qmake_all
sub-HumaBlotPro: $(MAKEFILE) FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-HumaBlotPro-make_first-ordered: sub-Instrument-make_first-ordered  FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-HumaBlotPro-make_first: FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-HumaBlotPro-all-ordered: sub-Instrument-all-ordered  FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-HumaBlotPro-all: FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-HumaBlotPro-clean-ordered: sub-Instrument-clean-ordered  FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-HumaBlotPro-clean: FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-HumaBlotPro-distclean-ordered: sub-Instrument-distclean-ordered  FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-HumaBlotPro-distclean: FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-HumaBlotPro-install_subtargets-ordered: sub-Instrument-install_subtargets-ordered  FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-HumaBlotPro-install_subtargets: FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-HumaBlotPro-uninstall_subtargets-ordered: sub-Instrument-uninstall_subtargets-ordered  FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-HumaBlotPro-uninstall_subtargets: FORCE
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Analysis-qmake_all: sub-HumaBlotPro-qmake_all FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	cd Analysis\ && $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && $(MAKE) -f Makefile qmake_all
sub-Analysis: $(MAKEFILE) FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Analysis-make_first-ordered: sub-HumaBlotPro-make_first-ordered  FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Analysis-make_first: FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Analysis-all-ordered: sub-HumaBlotPro-all-ordered  FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Analysis-all: FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Analysis-clean-ordered: sub-HumaBlotPro-clean-ordered  FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Analysis-clean: FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Analysis-distclean-ordered: sub-HumaBlotPro-distclean-ordered  FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Analysis-distclean: FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Analysis-install_subtargets-ordered: sub-HumaBlotPro-install_subtargets-ordered  FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Analysis-install_subtargets: FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Analysis-uninstall_subtargets-ordered: sub-HumaBlotPro-uninstall_subtargets-ordered  FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Analysis-uninstall_subtargets: FORCE
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: Solution.pro C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\win32-msvc\qmake.conf C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\spec_pre.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\common\angle.conf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\common\windows-vulkan.conf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\qconfig.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\qt_functions.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\qt_config.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\common\msvc-version.conf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\toolchain.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\default_pre.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\resolve_config.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\default_post.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\win32\console.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\resources.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\qtquickcompiler.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\precompile_header.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\warn_on.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\qmake_use.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\file_copies.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\exceptions.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\yacc.prf \
		C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\lex.prf \
		Solution.pro
	$(QMAKE) -o Makefile Solution.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\common\angle.conf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\common\windows-vulkan.conf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\qconfig.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_script.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\common\msvc-version.conf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\toolchain.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\default_post.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\win32\console.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\resources.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\qtquickcompiler.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\precompile_header.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\qmake_use.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\file_copies.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\exceptions.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\yacc.prf:
C:\Qt\Qt5.12.4\5.12.4\msvc2017_64\mkspecs\features\lex.prf:
Solution.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Solution.pro -spec win32-msvc "CONFIG+=qtquickcompiler"

qmake_all: sub-Theme-qmake_all sub-Utilities-qmake_all sub-Database-qmake_all sub-Model-qmake_all sub-DAO-qmake_all sub-BLL-qmake_all sub-Instrument-qmake_all sub-HumaBlotPro-qmake_all sub-Analysis-qmake_all FORCE

make_first: sub-Theme-make_first-ordered sub-Utilities-make_first-ordered sub-Database-make_first-ordered sub-Model-make_first-ordered sub-DAO-make_first-ordered sub-BLL-make_first-ordered sub-Instrument-make_first-ordered sub-HumaBlotPro-make_first-ordered sub-Analysis-make_first-ordered  FORCE
all: sub-Theme-all-ordered sub-Utilities-all-ordered sub-Database-all-ordered sub-Model-all-ordered sub-DAO-all-ordered sub-BLL-all-ordered sub-Instrument-all-ordered sub-HumaBlotPro-all-ordered sub-Analysis-all-ordered  FORCE
clean: sub-Theme-clean-ordered sub-Utilities-clean-ordered sub-Database-clean-ordered sub-Model-clean-ordered sub-DAO-clean-ordered sub-BLL-clean-ordered sub-Instrument-clean-ordered sub-HumaBlotPro-clean-ordered sub-Analysis-clean-ordered  FORCE
distclean: sub-Theme-distclean-ordered sub-Utilities-distclean-ordered sub-Database-distclean-ordered sub-Model-distclean-ordered sub-DAO-distclean-ordered sub-BLL-distclean-ordered sub-Instrument-distclean-ordered sub-HumaBlotPro-distclean-ordered sub-Analysis-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Theme-install_subtargets-ordered sub-Utilities-install_subtargets-ordered sub-Database-install_subtargets-ordered sub-Model-install_subtargets-ordered sub-DAO-install_subtargets-ordered sub-BLL-install_subtargets-ordered sub-Instrument-install_subtargets-ordered sub-HumaBlotPro-install_subtargets-ordered sub-Analysis-install_subtargets-ordered FORCE
uninstall_subtargets: sub-Theme-uninstall_subtargets-ordered sub-Utilities-uninstall_subtargets-ordered sub-Database-uninstall_subtargets-ordered sub-Model-uninstall_subtargets-ordered sub-DAO-uninstall_subtargets-ordered sub-BLL-uninstall_subtargets-ordered sub-Instrument-uninstall_subtargets-ordered sub-HumaBlotPro-uninstall_subtargets-ordered sub-Analysis-uninstall_subtargets-ordered FORCE

sub-Theme-debug_ordered:
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-Utilities-debug_ordered: sub-Theme-debug_ordered 
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-Database-debug_ordered: sub-Utilities-debug_ordered 
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-Model-debug_ordered: sub-Database-debug_ordered 
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DAO-debug_ordered: sub-Model-debug_ordered 
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-BLL-debug_ordered: sub-DAO-debug_ordered 
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-Instrument-debug_ordered: sub-BLL-debug_ordered 
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-HumaBlotPro-debug_ordered: sub-Instrument-debug_ordered 
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-Analysis-debug_ordered: sub-HumaBlotPro-debug_ordered 
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
debug: sub-Theme-debug_ordered sub-Utilities-debug_ordered sub-Database-debug_ordered sub-Model-debug_ordered sub-DAO-debug_ordered sub-BLL-debug_ordered sub-Instrument-debug_ordered sub-HumaBlotPro-debug_ordered sub-Analysis-debug_ordered

sub-Theme-release_ordered:
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-Utilities-release_ordered: sub-Theme-release_ordered 
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-Database-release_ordered: sub-Utilities-release_ordered 
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-Model-release_ordered: sub-Database-release_ordered 
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DAO-release_ordered: sub-Model-release_ordered 
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-BLL-release_ordered: sub-DAO-release_ordered 
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-Instrument-release_ordered: sub-BLL-release_ordered 
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-HumaBlotPro-release_ordered: sub-Instrument-release_ordered 
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-Analysis-release_ordered: sub-HumaBlotPro-release_ordered 
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
release: sub-Theme-release_ordered sub-Utilities-release_ordered sub-Database-release_ordered sub-Model-release_ordered sub-DAO-release_ordered sub-BLL-release_ordered sub-Instrument-release_ordered sub-HumaBlotPro-release_ordered sub-Analysis-release_ordered

sub-Theme-check_ordered:
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Utilities-check_ordered: sub-Theme-check_ordered 
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Database-check_ordered: sub-Utilities-check_ordered 
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Model-check_ordered: sub-Database-check_ordered 
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DAO-check_ordered: sub-Model-check_ordered 
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-BLL-check_ordered: sub-DAO-check_ordered 
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Instrument-check_ordered: sub-BLL-check_ordered 
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-HumaBlotPro-check_ordered: sub-Instrument-check_ordered 
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-Analysis-check_ordered: sub-HumaBlotPro-check_ordered 
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-Theme-check_ordered sub-Utilities-check_ordered sub-Database-check_ordered sub-Model-check_ordered sub-DAO-check_ordered sub-BLL-check_ordered sub-Instrument-check_ordered sub-HumaBlotPro-check_ordered sub-Analysis-check_ordered

sub-Theme-benchmark_ordered:
	@if not exist Theme\ mkdir Theme\ & if not exist Theme\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Theme\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Theme\Theme.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Utilities-benchmark_ordered: sub-Theme-benchmark_ordered 
	@if not exist Utilities\ mkdir Utilities\ & if not exist Utilities\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Utilities\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Utilities\Utilities.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Database-benchmark_ordered: sub-Utilities-benchmark_ordered 
	@if not exist Database\ mkdir Database\ & if not exist Database\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Database\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Database\Database.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Model-benchmark_ordered: sub-Database-benchmark_ordered 
	@if not exist Model\ mkdir Model\ & if not exist Model\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Model\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Model\Model.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DAO-benchmark_ordered: sub-Model-benchmark_ordered 
	@if not exist DAO\ mkdir DAO\ & if not exist DAO\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DAO\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\DAO\DAO.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-BLL-benchmark_ordered: sub-DAO-benchmark_ordered 
	@if not exist BLL\ mkdir BLL\ & if not exist BLL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BLL\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\BLL\BLL.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Instrument-benchmark_ordered: sub-BLL-benchmark_ordered 
	@if not exist Instrument\ mkdir Instrument\ & if not exist Instrument\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Instrument\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Instrument\Instrument.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-HumaBlotPro-benchmark_ordered: sub-Instrument-benchmark_ordered 
	@if not exist HumaBlotPro\ mkdir HumaBlotPro\ & if not exist HumaBlotPro\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd HumaBlotPro\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\HumaBlotPro\HumaBlotPro.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-Analysis-benchmark_ordered: sub-HumaBlotPro-benchmark_ordered 
	@if not exist Analysis\ mkdir Analysis\ & if not exist Analysis\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Analysis\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\liuxing\work\HumaBlotPro\HumaBlotPro_DXP\Analysis\Analysis.pro -spec win32-msvc "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Theme-benchmark_ordered sub-Utilities-benchmark_ordered sub-Database-benchmark_ordered sub-Model-benchmark_ordered sub-DAO-benchmark_ordered sub-BLL-benchmark_ordered sub-Instrument-benchmark_ordered sub-HumaBlotPro-benchmark_ordered sub-Analysis-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

