#ifndef SERIALPORTDRIVER_GLOBAL_H
#define SERIALPORTDRIVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALPORTDRIVER_LIBRARY)
#  define SERIALPORTDRIVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALPORTDRIVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALPORTDRIVER_GLOBAL_H
