#ifndef OBJECTINFO_H
#define OBJECTINFO_H

#define   ANSWER_COOMAND_TIMEOUT   10000
#define   SENSOR_LEFT              0x00
#define   SENSOR_RIGHT             0x01
#define   START_LIQUIDWAY		   0x01
#define   STOP_LIQUIDWAY		   0x00
#define   DIRECTION_LEFT           0x00
#define   DIRECTION_RIGHT          0x01
#define   SUCCEEDEDOVER             0 //成功
#define   SEND_COMMAND_ERR         -1 //发送命令失败
#define   ERRTHREADFAIL            -2 //线程错误
#define   ERRGENERATION            -5 //命令生成失败
#define   ERRWAITTIME              -6 //命令回复等待超时
#define   ERRBASECODE              -100 //其他错误基础码
#define   EACHMMSTEP               200
#define   INIT_EXITING_TIMEOUT     15000

/************************************************************************/
/*                    初始化状态                                         */
/************************************************************************/
enum
{
    INITIALIZE_UNDO,
    INITIALIZE_PROCESS ,
    INITIALIZE_FAIL,
    INITIALIZE_SUCCESS,
    INITIALIZE_STOP
};

enum
{
    CLEANINGPROCESS ,
    CLEANINGPROCESSFAIL,
    CLEANINGPROCESSSUCCESS,
    CLEANINGPROCESSSTOP
};

/************************************************************************/
/*                    反应盘电机地址                    */
/************************************************************************/
enum REACTION_MONTOR
{
    REACTION_DIS_MONTOR=0x12
};

enum
{
    REACTION_DIS_SPACING,
    REACTION_DIS_LOAD,
    REACTION_DIS_TRANSPORT,
    REACTION_DIS_SAMPLE,
    REACTION_DIS_ADD_REAGENT
};

/************************************************************************/
/*                   样本盘电机开关地址                                  */
/************************************************************************/
/************************************************************************/
/*                   样本臂电机开关地址                                  */
/************************************************************************/
enum SAMPLE_ARM_MONTOR
{
    SAMPLE_WASTE_PUMP=0x11,
    SAMPLE_VALUE_SV02=0x02,
    SAMPLE_VALUE_SV03=0x03,
    SAMPLE_PUMP_PU16=0x10,
    SAMPLE_PUMP_PU21=0x15
};

enum
{
    SAMPLE_ARM_POSTION,
    SAMPLE_ARM_WASH,
    SAMPLE_ARM_ADD,
    SAMPLE_ARM_WASH_HEIGHT,
    SAMPLE_ARM_SAMPLE_STAND_HEIGHT,
    SAMPLE_ARM_SAMPLE_BLOOD_HEIGHT,
    SAMPLE_ARM_SAMPLE_MICROCUP_HEIGHT,
    SAMPLE_ARM_ADD_HEIGHT
};



/************************************************************************/
/*                   试剂臂地址                                         */
/************************************************************************/
enum REAGENT_RAM
{
    REAGENT_WASTE_PUMPP=0x19,
    REAGENT_VALUE_SV05=0x05,
    REAGENT_VALUE_SV06=0x06,
    REAGENT_PUMP_PU18=0x12,
    REAGENT_PUMP_PU22=0x16
};

enum
{
    REAGENT_RAM_POSTION,
    REAGENT_RAM_WASH,
    REAGENT_RAM_ADD1,
    REAGENT_RAM_ADD2,
    REAGENT_RAM_ADD_MAGNENT1,
    REAGENT_RAM_ADD_MAGNENT2,
    REAGENT_ARM_WASH_HEIGNT,
    REAGENT_ARM_REAGENT_HEIGHT,
    REAGENT_ARM_MAGNENT1_HEIGHT,
    REAGENT_ARM_MAGNENT2_HEIGHT,
    REAGENT_ARM_REACTION_HEIGHT,
    REAGENT_ARM_SECOND_DOWN_HEIGHT
};



/************************************************************************/
/*                   清洗盘电机地址                                      */
/************************************************************************/
enum WASH_MONTOR
{
    WASH_VALUE_SV13 = 0x0D,
    WASH_PUMP_PU70 = 0x70,
    WASH_PUMP_PU31 = 0x31,
    WASH_PUMP_SV09 = 0x09,
    WASH_PUMP_SV10 = 0x0A,
    WASH_PUMP_SV11 = 0x0B,
    WASH_PUMP_SV12 = 0x0C,
    WASH_PUMP_PU73 = 0x73,
    WASH_PUMP_PU74 = 0x74,
    WASH_PUMP_PU75 = 0x75,
};

enum
{
    SUBSTRATE_AB,
    SUBSTRATE_CD,
    SUBSTRATE_SPIT,
    WASHING_HEIGHT,
    WASHING_START_WASTE_HEIGHT,
    WASHING_END_WASTE_HEIGHT
};

enum
{
    TRANSPORT_ARM_SPECIMENT_POSTION ,
    TRANSPORT_ARM_TAKE_IN_POSTION,
    TRANSPORT_ARM_TAKE_OUT_POSTION,
    TRANSPORT_ARM_TAKE_DROP_TUPE_POSTION,
    TRANSPORT_ARM_DETECT_POSTION,
    TRANSPORT_ARM_SPECIMEN_DISC_HEIGHT,
    TRANSPORT_ARM_WASH_HEIGHT,
    TRANSPORT_ARM_DROP_TUPE_HEIGHT,
    TRANSPORT_ARM_DETECTE_HEIGHT,
    TRANSPORT_ARM_SWITCH_OPEN
};

enum
{
    TRANSPORT_ARM_SENSOR_UNSHELTER,
    TRANSPORT_ARM_SENSOR_SHELTER,
    TRANSPORT_ARM_SENSOR_UNKNOWN
};//光电状态

enum
{
    //PC
    //装载单元。
    WARNING_PUT_TUBE_IN_REACTION_DISC_ENTRY_FAILED=0x0001,//放管到反应盘失败。
    WARNING_TUBE_STOREHOUSE_EMPTY=0x0002,//耗材库为空。
    WARNING_PUT_TUBE_IN_REACTION_DISC_ENTRY_CONFLICT=0x0003,//装载抓手放管到反应盘进管位冲突。
    WARNING_PUT_TUBE_IN_REACTION_DISC_ENTRY_SUCCESSION_CONFLICT=0x0004,//装载抓手放管到反应盘进管位严重冲突。
    WARNING_WASH_PUT_TUBE_IN_REACTION_DISC_ENTRY_FAILED=0x0005,//清洗/周维护/冲灌/排空时装载抓手反应盘放管失败
    WARNING_SUBSTRATE_PUT_TUBE_IN_REACTION_DISC_ENTRY_FAILED=0x0006,//底物测试时装载抓手反应盘放管失败
    WARNING_WASH_PUT_TUBE_IN_REACTION_DISC_ENTRY_CONFLICT=0x0007,//清洗/周维护/冲灌/排空时装载抓手放管到反应盘进管位冲突。
    WARNING_SUBSTRATE_PUT_TUBE_IN_REACTION_DISC_ENTRY_CONFLICT=0x0008,//底物测试时装载抓手放管到反应盘进管位冲突。
    //样本单元。
    WARNING_WITHOUT_SPECIMEN=0x03E9,//样本臂吸样过程中检测到样本量不足。
    WARNING_SUCCESSION_WITHOUT_SPECIMEN=0x03EA,//样本臂吸样过程中连续检测到样本量不足。
    WARNING_SPECIMEN_NEEDLE_SUCCESSION_BLOCKING=0x03EB,//样本针多次堵针。
    WARNING_SPECIMEN_BARCODE_OVERLONG=0x03EC,//样本条码超过最大长度限制。
    WARNING_SPECIMEN_NEEDLE_SUCCESSION_IMPACTING=0x03ED,//样本针多次撞针
    WARNING_WITHOUT_SPECIMEN_CLEANING_FLUID=0x03EE,//样本针清洗时清洗液不足
    //试剂单元。
    WARNING_WITHOUT_REAGENT=0x07D1,//试剂不足。
    WARNING_SUCCESSTION_WITHOUT_REAGENT=0x07D2,//连续试剂不足。
    WARNING_WITHOUT_MAGNETIC_BEAD=0x07D3,//磁珠不足。
    WARNING_SUCCESSTION_WITHOUT_MAGNETIC_BEAD=0x07D4,//连续磁珠不足。
    WARNING_REAGENT_DISK_TEMPERRATURE_ANOMALY=0x07D5,//试剂盘温度异常报警。
    WARNING_WITHOUT_REAGENT_NOTIMES=0x07D6,//试剂余量不足申请的项目
    WARNING_REAGENT_NEEDLE_SUCCESSION_IMPACTING=0x07D7,//试剂针连续撞针
    WARNING_REAGENT_DISC_OPEN=0x8802,//试剂盘盖当前是打开状态
    WARNING_REAGENT_DISC_CLOSE=0x8803,//试剂盘盖当前是关闭状态
    WARNING_WITHOUT_REAGENT_CLEANING_FLUID=0x07D8,//试剂针清洗时清洗液不足
    WARNING_REAGENT_BARCODE_OVERLONG=0x07D9,//试剂条码不是规定长度。
    WARNING_REAGENT_BARCODE_ITEMID_FAILED=0x07DA,//试剂条码中项目ID不存在。
    WARNING_REAGENT_BARCODE_DATE_FAILED=0x07DB,//试剂条码中日期字段是错误的。
    WARNING_REAGENT_BARCODE_ANALYSIS_FAILED=0x07DC,//试剂条码解析失败。
    //转运单元
    WARNING_TAKE_OUT_OF_REACTION_DISC_FAILED=0x0BB9,//转运抓手反应盘取管失败
    WARNING_RETURN_TO_REACTION_DISC_FAILED=0x0BBA,//转运抓手反应盘回管失败
    WARNING_RETURN_TO_REACTION_DISC_CONFLICT=0x0BBB,//转运抓手反应盘回管冲突
    WARNING_PUT_IN_WASHING_DISC_FAILED=0x0BBC,//转运抓手清洗盘放管失败
    WARNING_PUT_IN_WASHING_DISC_CONFLICT=0x0BBD,//转运抓手清洗盘放管冲突
    WARNING_TAKE_OUT_OF_WASHING_DISC_FAILED=0x0BBE,//转运抓手清洗盘取管失败
    WARNING_WITHOUT_TUBE_WHEN_TAKE_TUBE_OUT_OF_WASHING_DISC=0x0BBF,//清洗盘抓管时出管位无管
    WARNING_WITHOUT_TUBE_WHEN_TAKE_TUBE_OUT_OF_REACTION_DISC=0x0BC0,//反应盘抓管时出管位无管
    WARNING_INI_TAKE_OUT_OF_REACTION_DISC_FAILED=0x0BC1,//初始化时转运抓手反应盘取管失败
    WARNING_INI_TAKE_OUT_OF_WASH_DISC_FAILED=0x0BC2,//初始化时转运抓手清洗盘取管失败
    WARNING_WASH_PUT_IN_WASHING_DISC_FAILED=0x0BC3,//清洗/周维护/冲灌/排空时转运抓手清洗盘放管失败
    WARNING_WASH_WITHOUT_TUBE_WHEN_TAKE_TUBE_OUT_OF_WASHING_DISC=0x0BC4,//清洗/周维护/冲灌/排空时转运抓手清洗盘抓管时出管位无管
    WARNING_WASH_TAKE_OUT_OF_WASHING_DISC_FAILED=0x0BC5,//清洗/周维护/冲灌/排空时转运抓手清洗盘取管失败
    WARNING_SUBSTRATE_PUT_IN_WASHING_DISC_FAILED=0x0BC6,//底物测试时转运抓手清洗盘放管失败
    WARNING_SUBSTRATE_WITHOUT_TUBE_WHEN_TAKE_TUBE_OUT_OF_WASHING_DISC=0x0BC7,//底物测试时转运抓手清洗盘抓管时出管位无管
    WARNING_SUBSTRATE_TAKE_OUT_OF_WASHING_DISC_FAILED=0x0BC8,//底物测试时转运抓手清洗盘取管失败
    WARNING_WASH_PUT_IN_WASHING_DISC_CONFLICT=0x0BC9,//清洗/周维护/冲灌/排空时转运抓手清洗盘放管冲突
    WARNING_SUBSTRATE_PUT_IN_WASHING_DISC_CONFLICT=0x0BCA,//底物测试时转运抓手清洗盘放管冲突
    //检测单元
    WARNING_QUANTORECORDER_FAILURE=0x1389,//光子计数器错误（值为零）。
    WARNING_DETECTION_DISK_TEMPERRATURE_ANOMALY=0x138A,//检测盘温度异常报警。
    WARNING_DETECTION_DISK_TEMPERRATURE_ANOMALY_ERROR=0x138B,//检测盘温度异常错误。
    WARNING_SUBSTATE_QUANTORECORDER_FAILURE=0x138C,//底物测试光子计数器异常
    //系统错误
    WARNING_NOT_VALID_ERROR=0x7531,//无效错误。
    WARNING_UNKNOWN_ERROR=0x7532,//未知错误。
    WARNING_COMMUNICATION_ERROR=0x7533,//通讯错误警报。
    WARNING_SUCCESSION_TIMEOUT_ERROR=0x7534,//时序严重超时。
    PROMPT_TIMING_EXIT=0x7535, // 时序退出
    //液路
    WARNING_CLEANING_FLUID_DEFICIENCY_ERROR=0x1771,//清洗液桶清洗液不足。
    WARNING_WASTE_CAP_FULL_ERROR=0x1772,//废液桶满了。
    //反应单元
    WARNING_REACTION_DISK_TEMPERRATURE_ANOMALY=0x1B59,//反应盘温度异常报警。
    WARNING_REACTION_DISK_TEMPERRATURE_ANOMALY_ERROR=0x1B5A,//反应盘温度异常错误
    WARNING_LOAD_REACTION_DISK_FULL=0x1B5B,//装载抓手反应盘放管时反应盘无空位
    WARNING_TRANSPORT_REACTION_DISK_FULL=0x1B5C,//转运抓手反应盘放管时反应盘无空位
    //清洗单元
    WARNING_SUBSTRATE_NOTIMES=0x0FA1,//底物余量不足以申请新的项目
    //LIS功能模块
    WARNING_LIS_OPEN_FAILURE=0x7919,//LIS打开失败
    WARNING_LIS_SEND_FAILURE=0x791A,//LIS上传结果失败
    WARNING_LIS_QUERY_FAILURE=0x791B,//LIS查询样本检测信息失败
    //主控
    //装载单元
    WARNING_LOAD_TONG_PUT_TUBE_IN_TIMEOUT=0x8100,//装载抓手放管超时。
    WARNING_LOAD_TONG_PUT_TUBE_IN_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8101,//装载抓手放管下降时电机或光电传感器故障。
    WARNING_LOAD_TONG_PUT_TUBE_IN_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8102,//装载抓手放管上升时电机或光电传感器故障。
    WARNING_LOAD_TONG_PUT_TUBE_IN_TONG_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8103,//装载抓手放管时抓手电机或光电传感器故障。
    WARNING_LOAD_TONG_TAKE_TUBE_OUT_TIMEOUT=0x8104,//装载抓手取管超时。
    WARNING_TUBE_STOREHOUSE_MOTOR_PHOTOELECTRIC_SENSOR_FAILURE=0x8105,//耗材库电机或光电传感器故障。
    WARNING_LOAD_TONG_TAKE_TUBE_OUT_RESET_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8106,//装载抓手抓管时装载抓手水平电机或光电传感器故障（运动至复位位）。
    WARNING_LOAD_TONG_TAKE_TUBE_OUT_LEFT_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8107,//装载抓手抓管时装载抓手水平电机或光电传感器故障（运动至抓管位）。
    WARNING_LOAD_TONG_TAKE_TUBE_OUT_RIGHT_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8108,//装载抓手抓管时装载抓手水平电机或光电传感器故障（运动至反应盘）。
    WARNING_LOAD_TONG_TAKE_TUBE_OUT_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8109,//装载抓手抓管时装载抓手垂直电机或光电传感器故障（运动至装载台）。
    WARNING_LOAD_TONG_TAKE_TUBE_OUT_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x810A,//装载抓手抓管时装载抓手垂直电机或光电传感器故障（运动至复位位）。
    WARNING_LOAD_TONG_TAKE_TUBE_OUT_TONG_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x810B,//装载抓手抓管时装载抓手抓手电机或光电传感器故障。
    //反应单元。
    WARNING_REACTION_DISC_ROTATION_TIMEOUT=0x8110,//反应盘转动时动作超时。
    WARNING_REACTION_DISC_ROTATION_MOTOR_OR_CODER_FAILURE=0x8111,//反应盘转动时电机或编码器故障。
    WARNING_REACTION_DISC_RETURN_TO_ZERO_TIMEOUT=0x8112,//反应盘归零时动作超时。
    WARNING_REACTION_DISC_RETURN_TO_ZERO_MOTOR_OR_CODER_FAILURE=0x8113,//反应盘归零时电机或编码器故障。
    //样本单元
    WARNING_SPECIMEN_ARM_ADD_SPECIMEN_TIMEOUT=0x8120,//样本臂加样时动作超时。
    WARNING_SPECIMEN_ARM_ADD_SPECIMEN_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8121,//样本臂加样时样本臂垂直电机或光电传感器故障（运动至加样位）。
    WARNING_SPECIMEN_ARM_ADD_SPECIMEN_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8122,//样本臂加样时样本臂垂直电机或光电传感器故障（运动至复位位）。
    WARNING_SPECIMEN_ARM_SUCK_SPECIMEN_TIMEOUT=0x8123,//样本臂吸样时动作超时。
    WARNING_SPECIMEN_NEEDLE_BLOCKING=0x8124,//样本针堵针。
    WARNING_SPECIMEN_NEEDLE_SPITTING_BLOCKING=0x813E,//样本针吐样堵针。
    WARNING_SPECIMEN_ARM_LIQUID_LEVEL_DETECTION_BOARD_FAILURE=0x8125,//样本臂液位探测板故障。
    WARNING_SPECIMEN_ARM_SUCK_SPECIMEN_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8126,//样本臂吸样时样本臂垂直电机或光电传感器故障（运动至吸液位）。
    WARNING_SPECIMEN_ARM_SUCK_SPECIMEN_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8127,//样本臂吸样时样本臂垂直电机或光电传感器故障（运动至复位位）。
    WARNING_SPECIMEN_ARM_SUCK_SPECIMEN_MOVE_TO_SPECIMEN_DISC_HORIZONTAL_MOTOR_OR_CODER_FAILURE=0x8128,//样本臂吸样时样本臂水平电机或编码器故障（运动至样本位）。
    WARNING_SPECIMEN_ARM_SUCK_SPECIMEN_MOVE_TO_REACTION_DISC_HORIZONTAL_MOTOR_OR_CODER_FAILURE=0x8129,//样本臂吸样时样本臂水平电机或编码器故障（运动至反应盘）。
    WARNING_SPECIMEN_ARM_SUCK_SPECIMEN_PUMP_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x812F,//样本臂吸样时样本柱塞泵或光电传感器故障（吸样）。
    WARNING_SPECIMEN_ARM_WASH_TIMEOUT=0x812A,//样本臂清洗时动作超时。
    WARNING_SPECIMEN_ARM_WASH_HORIZONTAL_MOTOR_OR_CODER_FAILURE=0x812B,//样本臂清洗时样本臂水平电机或编码器故障。
    WARNING_SPECIMEN_ARM_WASH_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x812C,//样本臂清洗时样本臂垂直电机或光电传感器故障（运动至清洗位）。
    WARNING_SPECIMEN_ARM_WASH_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x812D,//样本臂清洗时样本臂垂直电机或光电传感器故障（运动至复位位）。
    WARNING_SPECIMEN_ARM_WASH_PUMP_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x812E,//样本臂清洗时样本柱塞泵或光电传感器故障（运动至复位位）。
    WARNING_SPECIMEN_DISC_ROTATION_TIMEOUT=0x8140,//样本盘转动时动作超时。
    WARNING_SPECIMEN_DISC_ROTATION_MOTOR_OR_CODER_FAILURE=0x8141,//样本盘转动时样本盘电机或编码器故障。
    WARNING_SPECIMEN_NEEDLE_SUCKING_IMPACTING_V=0x8130,//样本针垂直方向下降时发生撞针（吸样时）
    WARNING_SPECIMEN_NEEDLE_SUCKING_IMPACTING_H=0x8135,//样本针水平方向旋转时发生撞针（吸样时）
    WARNING_SPECIMEN_NEEDLE_SPTTING_IMPACTING_V=0x8131,//样本针垂直方向下降时发生撞针（加样时）
    WARNING_SPECIMEN_NEEDLE_WAHSING_IMPACTING_V=0x813C,//样本针垂直方向下降时发生撞针（清洗）
    WARNING_SPECIMEN_NEEDLE_WAHSING_IMPACTING_H=0x8136,//样本针水平方向旋转时发生撞针（清洗时）
    //试剂单元
    WARNING_REAGENT_ARM_ADD_REAGENT_TIMEOUT=0x8150,//试剂臂加样时动作超时。
    WARNING_REAGENT_ARM_ADD_REAGENT_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8151,//试剂臂加样时试剂臂垂直电机或光电传感器故障（运动至加液位）。
    WARNING_REAGENT_ARM_ADD_REAGENT_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8152,//试剂臂加样时试剂臂垂直电机或光电传感器故障（运动至复位位）。
    WARNING_REAGENT_ARM_SINGLE_SUCK_REAGENT_TIMEOUT=0x8153,//试剂臂单吸样时动作超时。
    WARNING_REAGENT_ARM_SINGLE_SUCK_REAGENT_LIQUID_LEVEL_DETECTION_BOARD_FAILURE=0x8154,//试剂臂液位探测板故障。
    WARNING_REAGENT_ARM_SINGLE_SUCK_REAGENT_MOVE_TO_REAGENT_DISC_HORIZONTAL_MOTOR_OR_CODER_FAILURE=0x8155,//试剂臂单吸样时试剂臂水平电机或编码器故障（运动至试剂位）。
    WARNING_REAGENT_ARM_SINGLE_SUCK_REAGENT_MOVE_TO_REACTION_DISC_HORIZONTAL_MOTOR_OR_CODER_FAILURE=0x8156,//试剂臂单吸样时试剂臂水平电机或编码器故障（运动至反应盘）。
    WARNING_REAGENT_ARM_SINGLE_SUCK_REAGENT_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8157,//试剂臂单吸样时试剂臂垂直电机或光电传感器故障（运动至吸液位）。
    WARNING_REAGENT_ARM_SINGLE_SUCK_REAGENT_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8158,//试剂臂单吸样时试剂臂垂直电机或光电传感器故障（运动至复位位）。
    WARNING_REAGENT_ARM_SINGLE_SUCK_REAGENT_PUMP_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8165,//试剂臂单吸样时试剂柱塞泵或光电传感器故障（吸样）。
    WARNING_REAGENT_ARM_DOUBLE_SUCK_REAGENT_TIMEOUT=0x8159,//试剂臂双吸样时动作超时。
    WARNING_REAGENT_ARM_DOUBLE_SUCK_REAGENT_LIQUID_LEVEL_DETECTION_BOARD_FAILURE=0x815A,//试剂臂液位探测板故障。
    WARNING_REAGENT_ARM_DOUBLE_SUCK_REAGENT_MOVE_TO_REAGENT_DISC_HORIZONTAL_MOTOR_OR_CODER_FAILURE=0x815B,//试剂臂双吸样时试剂臂水平电机或编码器故障（运动至试剂位）。
    WARNING_REAGENT_ARM_DOUBLE_SUCK_REAGENT_MOVE_TO_REACTION_DISC_HORIZONTAL_MOTOR_OR_CODER_FAILURE=0x815C,//试剂臂双吸样时试剂臂水平电机或编码器故障（运动至反应盘）。
    WARNING_REAGENT_ARM_DOUBLE_SUCK_REAGENT_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x815D,//试剂臂双吸样时试剂臂垂直电机或光电传感器故障（运动至吸液位）。
    WARNING_REAGENT_ARM_DOUBLE_SUCK_REAGENT_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x815E,//试剂臂双吸样时试剂臂垂直电机或光电传感器故障（运动至复位位）。
    WARNING_REAGENT_ARM_DOUBLE_SUCK_REAGENT_REAGENT_DISC_MOTOR_OR_CORDER_FAILURE=0x815F,//试剂臂双吸样时试剂盘电机或编码器故障。
    WARNING_REAGENT_ARM_DOUBLE_SUCK_REAGENT_PUMP_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8166,//试剂臂双吸样时试剂柱塞泵或光电传感器故障（吸样）。
    WARNING_REAGENT_ARM_WASH_TIMEOUT=0x8160,//试剂臂清洗时动作超时。
    WARNING_REAGENT_ARM_WASH_HORIZONTAL_MOTOR_OR_CODER_FAILURE=0x8161,//试剂臂清洗时试剂臂水平电机或编码器故障。
    WARNING_REAGENT_ARM_WASH_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8162,//试剂臂清洗时试剂臂垂直电机或光电传感器故障（运动至清洗位）。
    WARNING_REAGENT_ARM_WASH_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8163,//试剂臂清洗时试剂臂垂直电机或光电传感器故障（运动至复位位）。
    WARNING_REAGENT_ARM_WASH_PUMP_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8164,//试剂臂清洗时试剂柱塞泵或光电传感器故障（运动至复位位）。
    WARNING_REAGENT_NEEDLE_SUCKING_REAGENT_IMPACTING=0x8132,//试剂针垂直方向下降时发生撞针（吸试剂时）
    WARNING_REAGENT_NEEDLE_SUCKING_REAGENT_IMPACTING_H=0x8137,//试剂针水平方向旋转时发生撞针（吸试剂时）
    WARNING_REAGENT_NEEDLE_SUCKING_MAGNETIC_BEAD_IMPACTING=0x8133,//试剂针垂直方向下降时发生撞针（吸磁珠时）
    WARNING_REAGENT_NEEDLE_SPTTING_IMPACTING=0x8134,//试剂针垂直方向下降时发生撞针（加试剂时）
    WARNING_REAGENT_NEEDLE_WASHING_IMPACTING=0x813D,//试剂针垂直方向下降时发生撞针（清洗位）
    WARNING_REAGENT_NEEDLE_WASHING_IMPACTING_H=0x8138,//试剂针水平方向旋转时发生撞针（清洗时）
    WARNING_REAGENT_DISC_ROTATION_TIMEOUT=0x8170,//试剂盘转动时动作超时。
    WARNING_REAGENT_DISC_ROTATION_MOTOR_OR_CODER_FAILURE=0x8171,//试剂盘转动时样本盘电机或编码器故障。
    WARNING_REAGENT_DISC_REAG_BARCODE_FAILURE=0x8172,//试剂盘读条码错误。
    WARNING_MAGNETIC_BEAD_DISC_ROTATION_TIMEOUT=0x8180,//磁珠盘转动时动作超时。
    WARNING_MAGNETIC_BEAD_DISC_ROTATION_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8181,//磁珠盘转动时磁珠盘电机或光电传感器故障。
    //转运单元
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_REACTION_TIMEOUT=0x8190,//转运臂反应盘抓管时动作超时
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_REACTION_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8191,//转运臂反应盘抓管时转运臂垂直电机或光电传感器故障（运动至反应盘）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_REACTION_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8192,//转运臂反应盘抓管时转运臂垂直电机或光电传感器故障（运动至复位位）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_REACTION_TONG_OPEN_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8193,//转运臂反应盘抓管时转运臂抓手电机或光电传感器故障（抓手打开）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_REACTION_TONG_CLOSE_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8193,//转运臂反应盘抓管时转运臂抓手电机或光电传感器故障（抓手关闭）
    WARNING_TRANSPORT_TONG_RETURN_TUBE_TO_REACTION_TIMEOUT=0x8195,//转运臂反应盘放管时动作超时
    WARNING_TRANSPORT_TONG_RETURN_TUBE_TO_REACTION_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8196,//转运臂反应盘放管时转运臂垂直电机或光电传感器故障（运动至反应盘）
    WARNING_TRANSPORT_TONG_RETURN_TUBE_TO_REACTION_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8197,//转运臂反应盘放管时转运臂垂直电机或光电传感器故障（运动至复位位）
    WARNING_TRANSPORT_TONG_RETURN_TUBE_TO_REACTION_TONG_OPEN_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x8198,//转运臂反应盘放管时转运臂抓手电机或光电传感器故障（抓手打开）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_TIMEOUT=0x8199,//转运臂清洗盘抓管时动作超时
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x819A,//转运臂清洗盘抓管时转运臂垂直电机或光电传感器故障（运动至清洗盘）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x819B,//转运臂清洗盘抓管时转运臂垂直电机或光电传感器故障（运动至复位位）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_TO_WASH_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x819C,//转运臂清洗盘抓管时转运臂水平电机或编码器故障（运动至清洗盘出管位）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_TO_REACTION_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x819D,//转运臂清洗盘抓管时转运臂水平电机或编码器故障（运动至反应盘）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_TO_DETECTION_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x819E,//转运臂清洗盘抓管时转运臂水平电机或编码器故障（运动至检测盘）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_TONG_OPEN_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x819F,//转运臂清洗盘抓管时转运臂抓手电机或光电传感器故障（抓手打开）
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_TONG_CLOSE_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81A0,//转运臂清洗盘抓管时转运臂抓手电机或光电传感器故障（抓手关闭）
    WARNING_TRANSPORT_TONG_PUT_IN_WASH_TIMEOUT=0x81A1,//转运臂清洗盘放管时动作超时
    WARNING_TRANSPORT_TONG_PUT_IN_WASH_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81A2,//转运臂清洗盘放管时转运臂垂直电机或光电传感器故障（运动至清洗盘）
    WARNING_TRANSPORT_TONG_PUT_IN_WASH_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81A3,//转运臂清洗盘放管时转运臂垂直电机或光电传感器故障（运动至复位位）
    WARNING_TRANSPORT_TONG_PUT_IN_WASH_TO_WASH_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81A3,//转运臂清洗盘放管时转运臂水平电机或编码器故障（运动至清洗盘进管位）
    WARNING_TRANSPORT_TONG_PUT_IN_WASH_TO_REACTION_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81A5,//转运臂清洗盘放管时转运臂水平电机或编码器故障（运动至反应盘）
    WARNING_TRANSPORT_TONG_PUT_IN_WASH_TONG_OPEN_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81A6,//转运臂清洗盘放管时转运臂抓手电机或光电传感器故障（抓手打开）
    WARNING_TRANSPORT_TONG_PUT_IN_DETECTION_TIMEOUT=0x81A7,//转运臂检测盘放管动作超时。
    WARNING_TRANSPORT_TONG_PUT_IN_DETECTION_DOWN_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81A8,//转运臂检测盘放管时转运臂垂直电机或光电传感器故障（运动至检测盘）
    WARNING_TRANSPORT_TONG_PUT_IN_DETECTION_UP_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81A9,//转运臂检测盘放管时转运臂垂直电机或光电传感器故障（运动至复位位）
    WARNING_TRANSPORT_TONG_PUT_IN_DETECTION_TO_REACTION_HORIZONTAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81AA,//转运臂检测盘放管时转运臂水平电机或编码器故障（运动至反应盘）
    WARNING_TRANSPORT_TONG_PUT_IN_DETECTION_TONG_OPEN_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81AB,//转运臂检测盘放管时转运臂抓手电机或光电传感器故障（抓手打开)
    WARNING_TRANSPORT_TONG_PUT_IN_DETECTION_COVER_OPEN_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81AC,//转运臂检测盘放管时检测盘盖电机或光电传感器故障（检测盘盖打开)
    WARNING_TRANSPORT_TONG_PUT_IN_DETECTION_COVER_CLOSE_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81AD,//转运臂检测盘放管时检测盘盖电机或光电传感器故障（检测盘关闭)
    WARNING_TRANSPORT_TONG_TAKE_OUT_OF_WASH_DISC_IMPACTING=0x8139,//转运臂水平方向旋转时发生碰撞（清洗盘抓管）
    WARNING_TRANSPORT_TONG_PUT_IN_WASH_DISC_IMPACTING=0x813A,//转运臂水平方向旋转时发生碰撞（清洗盘放管）
    WARNING_TRANSPORT_TONG_PUT_IN_DETECTION_DISC_IMPACTING=0x813B,//转运臂水平方向旋转时发生碰撞（检测盘放管）
    //清洗单元
    WARNING_WASHING_DISC_ROTATION_TIMEOUT=0x81B0,//清洗盘转动时动作超时。
    WARNING_WASHING_DISC_ROTATION_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81B1,//清洗盘转动时清洗盘电机或光电传感器故障。
    WARNING_WASHING_DISC_WASHING_TIMEOUT=0x81B2,//清洗站清洗时动作超时。
    WARNING_WASHING_DISC_WASHING_MOVE_TO_START_DRAIN_POSITION_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81B3,//清洗站清洗时清洗站升降电机或光电传感器故障（运动至开始排液位）。
    WARNING_WASHING_DISC_WASHING_MOVE_TO_STOP_DRAIN_POSITION_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81B4,//清洗站清洗时清洗站升降电机或光电传感器故障（运动至结束排液位）。
    WARNING_WASHING_DISC_WASHING_MOVE_TO_SUBSTRATE_POSITION_VERTICAL_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81B5,//清洗站清洗时清洗站升降电机或光电传感器故障（运动至加底物位）。
    WARNING_WASHING_DISC_WASHING_MOVE_TO_SUBSTRATE_POSITION_SUBSTRATE_ROTATION_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81B6,//清洗站清洗时底物旋转电机或光电传感器故障（运动至底物位）。
    WARNING_WASHING_DISC_WASHING_MOVE_TO_DRAIN_POSITION_SUBSTRATE_ROTATION_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81B7,//清洗站清洗时底物旋转电机或光电传感器故障（运动至排液位）。
    WARNING_WASHING_DISC_WASHING_MOVE_TO_RESET_POSITION_SUBSTRATE_ROTATION_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81B8,//清洗站清洗时底物旋转电机或光电传感器故障（运动至复位位）。
    //检测单元
    WARNING_DETECTION_DISC_ROTATION_TIMEOUT=0x81C0,//检测盘转动时动作超时。
    WARNING_DETECTION_DISC_ROTATION_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81C1,//检测盘转动时检测盘电机或光电传感器故障。
    WARNING_DETECTION_DISC_DROP_TUBE_TIMEOUT=0x81C2,//掉管机构掉管时动作超时。
    WARNING_DETECTION_DISC_MOVE_TO_DROP_POSITION_DROP_TUBE_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81C3,//掉管机构掉管时掉管电机或光电传感器故障（运动至掉管位）。
    WARNING_DETECTION_DISC_MOVE_TO_RESET_POSITION_DROP_TUBE_MOTOR_OR_PHOTOELECTRIC_SENSOR_FAILURE=0x81C4,//掉管机构掉管时掉管电机或光电传感器故障（运动至复位位）。
    //液路
    WARNING_LIQUID_WAY_CANNOT_IRRIGATION_FINISHED=0x81D0,//缓冲池无法完成充灌。未接清洗液或缓冲瓶上浮子故障或进液泵故障。
    WARNING_LIQUID_WAY_CANNOT_IRRIGATION=0x81D1,//缓冲池无法完成充灌。未接清洗液或缓冲瓶下浮子故障或进液泵故障。
    //控制
    WARNING_SCRAM=0x8800,//急停。
    WARNING_INSTRUMENT_RESET=0x8801,//设备复位。
};//警告

#endif // OBJECTINFO_H
